### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by HelloWorld017** [HelloWorld017/osu-Player#1]
- [x] Add support for mobile devices.
- [x] Add progress bar.
- [x] Add lyric.
- [x] Add preferences.
- [x] Add .playing implementation.
- [x] Add error() implementation.
- [x] Add playlist options.
